### ISSUE TITLE
Type Error in collect_activations() w/ resnet50-v1-13.onnx

### ISSUE THREAD

**Issue by woojoo99** [microsoft/onnxruntime-inference-examples#198]
I tested https://github.com/microsoft/onnxruntime-inference-examples/tree/main/quantization/image_classification/cpu/run_qdq_debug.py, with resnet50-v1-13.onnx.

I preprocessed the onnx file with option --skip_symbolic_shape True as in ReadMe.md.
Then running run_qdq_debug.py, I can see an error in collect_activations:

> Running the augmented qdq model to collect activations......
> Traceback (most recent call last):
>   File "run_qdq_debug.py", line 90, in <module>
>     main()
>   File "run_qdq_debug.py", line 77, in main
>     qdq_activations = collect_activations(aug_qdq_model_path, input_data_reader)
>   File "/home/hwkim/.local/lib/python3.8/site-packages/onnxruntime/quantization/qdq_loss_debug.py", line 138, in collect_activations
>     inference_session = onnxruntime.InferenceSession(
>   File "/home/hwkim/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
>     self._create_inference_session(providers, provider_options, disabled_optimizers)
>   File "/home/hwkim/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 384, in _create_inference_session
>     sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
> onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from resnet50-qt.save_tensors.onnx failed:Type Error: Type (tensor(uint8)) of output arg (data_QuantizeLinear_Output) of node (data_QuantizeLinear) does not match expected type tensor(int8)).

collect_activations() works well in collecting float model activations, but doesn't in collecting qdq model activations. So weird...

onnx: v1.13.0
onnxruntime: v1.13.1
OS: Ubuntu 20.04 LTS

**Comment by chenfucn** [comment]
onnx shape inference produces wrong results for this model, this is indeed very strange.
QuantizeLinear node output type should have the same element type as the zeropoint input. However, here the output is assigned uint8 type by the shape inference, yet the zeropoint is of type int8. The problem comes from this call:

onnx.shape_inference.infer_shapes_path("resnet50-v1-13-quant.onnx", "resnet50-v1-13-quant-inferred.onnx")

This call goes from python into c library. I am seeking help on how to debug this.

**Comment by chenfucn** [comment]
https://github.com/microsoft/onnxruntime-inference-examples/pull/222

Looks like this model file has an ir-version of 3 and opset version of 13. This seems to cause trouble with onnx shape inference. Removing this model, other models from https://github.com/onnx/models/tree/main/vision/classification/resnet/model work fine.
