### ISSUE TITLE
does not work with models other than openai/whisper-tiny.en

### ISSUE THREAD

**Issue by marouanetalaa** [microsoft/onnxruntime-inference-examples#335]
Error: Unknown input name audio_pcm, expected one of [audio_stream, max_length, min_length, num_beams, num_return_sequences, length_penalty, repetition_penalty]

`Error: Unknown input name audio_pcm, expected one of [audio_stream, max_length, min_length, num_beams, num_return_sequences, length_penalty, repetition_penalty]
                                                                                                    ai.onnxruntime.OrtException: Unknown input name audio_pcm, expected one of [audio_stream, max_length, min_length, num_beams, num_return_sequences, length_penalty, repetition_penalty]
                                                                                                    	at ai.onnxruntime.OrtSession.run(OrtSession.java:284)
                                                                                                    	at ai.onnxruntime.OrtSession.run(OrtSession.java:242)
                                                                                                    	at ai.onnxruntime.OrtSession.run(OrtSession.java:210)
                                                                                                    	at com.alex.newnotes.utils.SpeechRecognizer.run(SpeechRecognizer.kt:40)
                                                                                                    	at com.alex.newnotes.utils.AudioTensorSource$Companion.fromRecording(AudioTensorSource.kt:118)
                                                                                                    	at com.alex.newnotes.ui.edit.EditFragment.addSpeech$lambda-28(EditFragment.kt:454)
                                                                                                    	at com.alex.newnotes.ui.edit.EditFragment.$r8$lambda$imHSLHbY2ngBNrJv8EgIh9aj6Dg(Unknown Source:0)
                                                                                                    	at com.alex.newnotes.ui.edit.EditFragment$$ExternalSyntheticLambda11.run(Unknown Source:2)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
`

**Comment by edgchen1** [comment]
the model used in the Whisper example was created by Olive without the audio decoder included. in that case, the input name is "audio_pcm". looks like this error comes from using a model created with the audio decoder included.

https://github.com/microsoft/Olive/blob/3a74d46a752957e891c016623b25d6f45e254666/examples/whisper/code/whisper_dataset.py#L35-L43
