### ISSUE TITLE
Issues with Running 'e2e_tensorrt_resnet_example.py' Example

### ISSUE THREAD

**Issue by TouqeerAhmad** [microsoft/onnxruntime-inference-examples#407]
Hello, I am trying to run the end-to-end quantization example for ResNet50 using TRT EP and facing couple of issues. The first problem I am facing is 'compute_range' attribute is not available in 'MinMaxCalibrater'. 

<img width="1215" alt="Screenshot 2024-03-29 at 8 50 04 AM" src="https://github.com/microsoft/onnxruntime-inference-examples/assets/5327052/1a0f456e-0c82-4659-9f74-421a49dc7067">

When I comment the 'write_calibration_table(calibrator.compute_range())', I get another which is again probably due to the first one as It shows an exception: "Failed to read INT8 calibration table calibration.flatbuffers" 

<img width="2219" alt="Screenshot 2024-03-29 at 8 50 59 AM" src="https://github.com/microsoft/onnxruntime-inference-examples/assets/5327052/819f5a2d-5d3d-4a44-ae63-7d5a337345aa">

was wondering if somebody have an insight, thanks!

**Comment by TouqeerAhmad** [comment]
I was finally able to run it by setting up an environment with an older version of onnxruntime-gpu, specifically 1.31.1

**Comment by TouqeerAhmad** [comment]
I have tried running this example with onnxruntime-gpu==1.14.0, and tensorrt==8.5.1.7, I see a reduced top1 accuracy of 0.710 when using TensorrtExecutionProvider, compared to 0.739 when I use CUDAExecutionProvider. However, the inference time for TensorrtExecutionProvider is more than CUDAExecutionProvided which I was not expecting. 

Any advise? 

PS: The ResNet50 tutorial with TensorRT significantly lags documentation. Also, these needs to be updated with latest onnxruntime and tensorrt versions or at least list information at the time of writing which versions were used.

**Comment by liopeer** [comment]
I am facing issues with this example as well. The links are outdated and I get an error with the synset ID:

```
Traceback (most recent call last):
  File "/home/lightly/lionel/onnxruntime-inference-examples/quantization/image_classification/trt/resnet50/e2e_tensorrt_resnet_example.py", line 356, in <module>
    synset_id = data_reader.get_synset_id(ilsvrc2012_dataset_path, calibration_dataset_size,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lightly/lionel/onnxruntime-inference-examples/quantization/image_classification/trt/resnet50/e2e_tensorrt_resnet_example.py", line 193, in get_synset_id
    synset_id = np.array([synset_to_id[id_to_synset[index]] for index in id])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lightly/lionel/onnxruntime-inference-examples/quantization/image_classification/trt/resnet50/e2e_tensorrt_resnet_example.py", line 193, in <listcomp>
    synset_id = np.array([synset_to_id[id_to_synset[index]] for index in id])
                          ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: np.str_('n02095314')
```

Would really appreciate if this was updated, since it's a pain to get running and there's not many quantization examples out there. 🙏
