### ISSUE TITLE
OnnxRuntime does not work when running on real iPhone - The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception.

### ISSUE THREAD

**Issue by codingzerotohero** [microsoft/onnxruntime-inference-examples#455]
.NET MAUI - testing on Local iPhone 11 with Hot Restart and Apple Developer membership, connected with USB cable.

_session = new InferenceSession(_model) always results in this exception:
The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception.

The model is properly retrieved from the .onnx file before being send in to InferenceSession as parameter according to logs.

Logs:
2024-08-09 13:59:36.405 Xamarin.PreBuilt.iOS[3339:683336] AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
2024-08-09 13:59:36.405 Xamarin.PreBuilt.iOS[3339:683336] The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception.

2024-08-09 13:59:36.406 Xamarin.PreBuilt.iOS[3339:683336]    at Microsoft.ML.OnnxRuntime.NativeMethods..cctor()

2024-08-09 13:59:36.406 Xamarin.PreBuilt.iOS[3339:683336]    at Microsoft.ML.OnnxRuntime.SessionOptions..ctor()
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(Byte[] model)
2024-08-09 13:59:36.406 Xamarin.PreBuilt.iOS[3339:683336]    at MauiApp11111.VisionSampleBase`1.<Initialize>d__23[[MauiApp11111.MobilenetImageProcessor, MauiApp11111, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() in C:\Users\asd\source\repos\MauiApp11111\MauiApp11111\VisionSampleBase.cs:line 113
2024-08-09 13:59:36.406 Xamarin.PreBuilt.iOS[3339:683336] __Internal

2024-08-09 13:59:36.396 Xamarin.PreBuilt.iOS[3339:683336] LENGTH: 13964571

I added a try catch to get the exception:
![image](https://github.com/user-attachments/assets/680908c4-9001-47dc-b016-77250a793141)

I have tried many different ways, like also creating my own fresh .NET MAUI project and setting it up from scratch. I still get that exact exception when using new InferenceSession. On the fresh project I also tried with my own trained PyTorch model converted to .onnx format, still getting same error.

It seems the only way this works, according to what I've seen online, is when running OnnxRuntime on iOS Simulator, but not on an actual iPhone.

**Comment by codingzerotohero** [comment]
This is caused by limitation of Hot Restart, which makes it that native libraries (like onnxruntime) are not added to the app.
