### ISSUE TITLE
Memory leak in examples for C++ in your project.

### ISSUE THREAD

**Issue by EjenY-Poltavchiny** [microsoft/onnxruntime-inference-examples#457]
Hi, there!
I've started to work with onnxruntime lib aproximately 2 mounth ago. I've tried to search for documentation for `C++` and found some inferencing examples from `ultralitycs` and others (including your `examples`). After all i succesfuly run model inferencing and spent some time for postprocessing. However, I decided to check my code for memory leaks and other problems using `clang` sanitizer and found some `memory leaks`. After endless attempts to fix it, I still didn't understand why my code causes memory leaks, so i decided to check docs examples for `memory leaks`. And `clang` sanitizer found it:
```bash
==3972466==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7fc26e8d5a57 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x7fc26e3b4df9  (/usr/local/lib/libonnxruntime.so.1.18.0+0xa2cdf9)

Direct leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7fc26e8d5a57 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x7fc26e3b4ddd  (/usr/local/lib/libonnxruntime.so.1.18.0+0xa2cddd)
```
I've used [this](https://github.com/microsoft/onnxruntime-inference-examples/blob/main/c_cxx/model-explorer/batch-model-explorer.cpp) example.
This was my `Cmake`:
```cmake
cmake_minimum_required(VERSION 3.5)

set(PROJECT_NAME Yolov8OnnxRuntimeCPPInference)
project(${PROJECT_NAME} VERSION 0.0.1 LANGUAGES CXX)

add_executable(Yolov8OnnxRuntimeCPPInference main.cpp)
target_link_libraries(Yolov8OnnxRuntimeCPPInference PRIVATE onnxruntime)

target_compile_options(Yolov8OnnxRuntimeCPPInference PRIVATE -fsanitize=address)
target_link_options(Yolov8OnnxRuntimeCPPInference PRIVATE -fsanitize=address)
``` 
Interesting fact - if i will run this code it will still cause `memory leaks`:
```cpp
int main() {
  // onnxruntime setup
  Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "example-model-explorer");
  return 0;
```

Or this one:
```cpp
int main() {
  // onnxruntime setup
  for (int i = 0; i < 10; ++i) {
    Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "example-model-explorer");
  }
  return 0;
```

They all will cause the same leak with no explainings (i've tried to find symbols by adress that sanitizer gives me, but it was no use)
```bash
==3991181==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7f353d9ffa57 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x7f353d4dedf9  (/usr/local/lib/libonnxruntime.so.1.18.0+0xa2cdf9)

Direct leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7f353d9ffa57 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x7f353d4deddd  (/usr/local/lib/libonnxruntime.so.1.18.0+0xa2cddd)

SUMMARY: AddressSanitizer: 256 byte(s) leaked in 2 allocation(s).
```

**Comment by tianleiwu** [comment]
@snnn, any idea of memory leak?

**Comment by snnn** [comment]
Might be a false alarm.
See: https://github.com/microsoft/onnxruntime/issues/20803#issuecomment-2135832348

Please build the binary locally with symbols. Then run the example again. You will either see the "memory leak" is gone, or you will get a full stacktrace.
