### ISSUE TITLE
My with_pre_post_processing.onnx by yolov8n.pt transfored to onnx can't work

### ISSUE THREAD

**Issue by 9479421** [microsoft/onnxruntime-inference-examples#458]
The onnx file in the examples is work:
https://github.com/microsoft/onnxruntime-inference-examples/tree/main/mobile/examples/object_detection/android
but I use oridinal yolov8n.pt to transfor yolov8n.onnx, and transfor .onnx to with_pre_post_processing.onnx  can't work. When execute
 'val inputTensor = OnnxTensor.createTensor(
            ortEnv,
            ByteBuffer.wrap(rawImageBytes),
            shape,
            OnnxJavaType.UINT8
        )
'
it will throw Exception
'Exception caught when perform ObjectDetection
                                                                                                    ai.onnxruntime.OrtException: Unexpected number of requestedOutputs & pinnedOutputs, expected [1,1) found 2
                                                                                                    	at ai.onnxruntime.OrtSession.run(OrtSession.java:341)
                                                                                                    	at ai.onnxruntime.OrtSession.run(OrtSession.java:242)
                                                                                                    	at ai.onnxruntime.example.objectdetection.ObjectDetector.detect(ObjectDetector.kt:45)
                                                                                                    	at ai.onnxruntime.example.objectdetection.MainActivity.performObjectDetection(MainActivity.kt:123)
                                                                                                    	at ai.onnxruntime.example.objectdetection.MainActivity.onCreate$lambda$0(MainActivity.kt:61)'

who can help me , My English is not good, thanks for every friends who can help me

**Comment by wejoncy** [comment]
hi, @9479421 

The model used in this example has two outputs, 1) image with bounding-box, 2) the coordinate 
If you want to run this example with your own yolo-model, Please run the tool following such changes
https://github.com/microsoft/onnxruntime-extensions/issues/480#issuecomment-1641225896

**Comment by iamxiaojuan** [comment]
@wejoncy  
After I added **Debug(),** like you said, it didn't output "**scaled_box_out_next**". As shown in the figure:

![Image](https://github.com/user-attachments/assets/faa9a6d8-a285-4f8c-bcaf-3874c02fbfd0)
（The code version is **main**）


The figure shows my changes to "add_pre_post_processing_to_model"：

![Image](https://github.com/user-attachments/assets/2bbaa06c-0ada-435f-80dc-f8c5a0c82264)

Please help me.

**Comment by wejoncy** [comment]
@iamxiaojuan Is your model a object detection model?

**Comment by iamxiaojuan** [comment]
Yes, the model was downloaded from the yolo website @wejoncy

**Comment by wejoncy** [comment]
@iamxiaojuan  
The name in model output changed to 'nms_output_with_scaled_boxes_and_keypoints_next' indeed.  
You can change the name in the example java code to match it.

**Comment by iamxiaojuan** [comment]
@wejoncy My problem is solved. Thank you very much!
